Vagrant.configure(2) do |config|  # the literal "2" is required.
    config.vm.box = "Microsoft/EdgeOnWindows10"
    config.vm.box_version = "1.0"
    config.vm.hostname = "windows10.test"
    config.vm.network "private_network", ip: "172.17.2.10"
    config.vm.communicator = "winrm"
    config.winrm.password = "Passw0rd!"
    config.winrm.username = "IEUser"
    # config.vm.network "forwarded_port",
    #   host: 33389,
    #   guest: 3389,
    #   id: "rdp",
    #   auto_correct: true
end
