#
# This Vagrantfile sets up a Windows machine configured to work with the
#  supplied demo Vagrant-powered Bevy Master.
#
Vagrant.configure(2) do |config|  # the literal "2" is required.
    config.vm.box = "Microsoft/EdgeOnWindows10"  # a time-limited
    config.vm.box_version = "1.0"
    config.vm.hostname = "windows10.test"

    config.vm.provider "virtualbox" do |v|
        v.name = 'win10_edge'  # ! N.O.T.E.: name must be unique
        v.gui = true  # turn on the graphic window
        v.linked_clone = true
        v.customize ["modifyvm", :id, "--vram", "18"]  # enough video memory for full screen
        # v.memory = 4096
        # v.cpus = 2
    end
    config.vm.network "private_network", ip: "172.17.2.10"  # N.O.T.E: must be unique.
    # on your Windows guest - your shared \vagrant folder will be found on `Network --> VBOXSVR`

    config.vm.guest = :windows
    config.vm.communicator = "winrm"
    config.vm.boot_timeout = 600
    config.vm.graceful_halt_timeout = 600
    config.winrm.password = "Passw0rd!"
    config.winrm.username = "IEUser"

    # config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
    #config.vm.network "forwarded_port",
    #    host: 33389,
    #    guest: 3389,
    #    id: "rdp",
    #    auto_correct: true
end
